version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  vend:
    lang: golang-middleware
    handler: ./vend
    image: vend:latest

configuration:
  templates:
    - name: golang-middleware
  no-modules:
    lang: golang-middleware
    handler: ./no-modules
    image: no-modules:latest

